### ISSUE TITLE
Keyboard stops responding when Alt-Tab is pressed

### ISSUE THREAD

**Issue by ssb22** [scarybeasts/beebjit#11]
On a Fedora 31 box, if I press Alt-Tab to switch from the BBC Micro window to another window, when I switch back to the BBC Micro window the keyboard input no longer works.  Problem reproduced when running `beebjit` with no parameters and trying to type at the BASIC prompt before and after the Alt-Tab.

There is no problem if I use the mouse to switch from the BBC Micro window to another window, and then Alt-Tab back to the BBC Micro window.  So it seems using Alt-Tab to switch *out* of the window is what's causing the problem.

If this cannot be fixed, then perhaps it can be documented as a limitation (i.e. just tell everyone to use the mouse and not the keyboard when switching to another window)?

**Comment by scarybeasts** [comment]
Thanks. Yeah, happens to me on an older Ubuntu here.

What is happening is the Alt key is getting stuck in the down state because a key up event is never received due to the loss of focus. As a quick workaround, you can just press Alt when the window is back in focus.

I should be able to fix this by listening for loss of focus and if alt is down, force a key up for all keys that are down.

**Comment by scarybeasts** [comment]
Should be addressed on master.

**Comment by ssb22** [comment]
Thanks!  Works for me now as well.
